---
# tasks file for lvreduce
- name: Reducing the attributes of the logical volume
  lv: action={{item.action}}
      force={{item.force}}
      vgname={{item.vgname}}
      lvname={{item.lvname}}
      nofsck={{item.nofsck}}
      resizefs={{item.resizefs}}
      size={{item.size}}
      pvname={{item.pvname}}
  with_items:
  - "{{ lvreduce_list }}"
