---
# tasks file for vgconvert
- name: Converting a volume group
  vg: action={{item.action}}
      vgname={{item.vgname}}
      metadatatype={{item.metadatatype}}
  with_items:
  - "{{ vgconvert_list }}"
