---
- hosts: rhs_servers
  remote_user: root
  gather_facts: no

  tasks:
      - name: Check if nfs-ganesha is installed
        shell: rpm -q nfs-ganesha
        register: rpm_check

      - debug: msg="Package nfs-ganesha is not installed"
        when: rpm_check.rc != 0

      - name: Check if corosync is installed
        shell: rpm -q corosync
        register: rpm_check

      - debug: msg="Package corosync is not installed"
        when: rpm_check.rc != 0

      - name: Check if pacemaker is installed
        shell: rpm -q pacemaker
        register: rpm_check

      - debug: msg="Package pacemaker is not installed"
        when: rpm_check.rc != 0
