---
- hosts: clients
  remote_user: root
  gather_facts: no

  tasks:
  - name: Unmount the volumes
    mount: name="{{ client_mount_points }}" src="{{ client_mount_points }}" fstype=xfs
           state=unmounted

  - name: Delete the mount points
    shell: rm -rf "{{ client_mount_points }}"
