---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  - name: Get the key from local to remote
    copy: src={{ item }}/var/lib/glusterd/nfs/secret.pem.pub
          dest=/tmp/key
    with_items: master_node

  - name: Copy the public key from local to remote
    copy: src={{ item }}/var/lib/glusterd/nfs/secret.pem.pub
          dest=/var/lib/glusterd/nfs/
    with_items: master_node
    ignore_errors: true

  - name: Deploy the pubkey ~/root/.ssh/authorized_keys on all nodes
    shell: cat /tmp/key >> ~/.ssh/authorized_keys

  - name: Remove the unwanted copy of key
    shell: rm -rf ~/tmp/key
