---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Generate ssh key in one of the nodes in HA cluster
    shell: ssh-keygen -f /var/lib/glusterd/nfs/secret.pem -y -t rsa -N ''

  - name: Copy the public key to the local
    fetch: src=/var/lib/glusterd/nfs/secret.pem.pub
           dest=/tmp/playbooks
