---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Sets options for volume
    volume-set: action=set
                volume="{{ volname }}"
                key={{ item }} value="{{ value }}"
    with_items: "{{ key }}"
