---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Stops a volume
    volume: action=stop
             volume="{{ volname }}"

  - name: Deletes a volume
    volume:  action=delete
             volume="{{ volname }}"
