---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Stops a volume
    gluster: command=volume action=stop
             volume="{{ volname }}"

  - name: Deletes a volume
    gluster: command=volume action=delete
             volume="{{ volname }}"
