---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Creates a snapshot
    gluster: command=snapshot action=create
             volume="{{ volname }}"
             snapname="{{ snapname }}"
             force=yes
