---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Deactivates a snapshot
    gluster: command=snapshot action=deactivate
             snapname=snap1
             force=yes
