---
- hosts: rhs_servers
  remote_user: root
  gather_facts: no

  tasks:
  - name: Unmount the volumes
    mount: name={{ item }} src={{ item }} fstype=xfs
           state=unmounted
    with_items: mountpoints

  - name: Delete the mount points
    shell: rm -rf {{ item }}
    with_items: mountpoints
