---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  - name: Unmount the volumes
    mount: name={{ item.path }} src={{ item.path }} fstype=xfs
           state=unmounted
    with_items: mntpath

  - name: Delete the mount points
    shell: rm -rf {{ item.path }}
    with_items: mntpath
