---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  - name: Installs/Removes a package using yum and enable repos
    yum: name={{ item }} state="{{ yum_state }}" disable_gpg_check="{{ gpgcheck }}"
         enablerepo="{{ enabled_repos }}"
    with_items: name
    when: name is defined and yum_state is defined
    when: enabled_repos is defined and enabled_repos|length > 0

  - name: Installs/Removes a package using yum
    yum: name={{ item }} state="{{ yum_state }}"
    with_items: name
    when: name is defined and yum_state is defined
    when: enabled_repos is not defined or enabled_repos|length == 0

