---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Creates a volume with a single host
    gluster: command=volume action=create
             volume=volname
             bricks='{% for host in hosts %}
             {{ hostvars[host]['mountpoints'] }}
             {% endfor %}'
             hosts="{{ hosts }}"
             current_host={{inventory_hostname}}
             force=yes
