---
- hosts: georep_master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Create the geo-rep session
    geo_rep: action=create
            mastervol="{{ mastervolname }}"
            slavevol="{{ slavevol }}"
            force="{{ force }}"
            georepuser="{{ georepuser }}"
