---
- hosts: georep_master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Resume the geo-rep session
    geo_rep: action=resume
            mastervol="{{ mastervolname }}"
            slavevol="{{ slavevol }}"
            georepuser="{{ georepuser }}"
            force="{{ force }}"
