---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Add bricks to an existing volume
    volume:  action=add-brick
             volume="{{ volname }}"
             bricks="{{ mountpoints }}"
             replica_count="{{ replica_count }}"
             force="{{ force }}"
