---
- hosts: clients
  remote_user: root
  gather_facts: no

  tasks:
  - name: Create the dir to mount the volume, skips if present
    file: path={{ item.mountpoint }} state=directory
    when: item.fstype == 'cifs'

    with_items: client_mounts

  - name: Mount the volumes
    mount: name={{ item.mountpoint }}
           src="\\\\{{ groups['master'][0]}}\\gluster-{{ volname }}"
           fstype="cifs"
           opts="username={{smb_username}},password={{smb_password}}"
           state=mounted
    when: item.fstype == 'cifs'

    with_items: client_mounts

