---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
   - name: Get the heketi service IP
     kubectl: action=get type=service name=heketi
     register: result
     when: servername is not defined or not servername

   - set_fact: servername="http://{{result["msg"].split('\\n')[1].split()[1]}}:{{port}}"
     when: (servername is not defined or not servername) and result["msg"].split('\\n')[1].split()[1] is defined

   - fail: msg="Could not find the IP of heketi service running"
     when: servername is not defined

---
- hosts: master
  remote_user: root
  gather_facts: no
  connection: local

  tasks:
  - name: Add devices to heketi nodes
    heketi: action=adddevice user="{{ user }}"  userkey="{{ user_key }}" server="{{ servername }}"
            node="{{ node }}" devices="{{ item.devices }}"
    with_items: hdict
    register: result

  - debug: msg="{{ result.results[0]['msg'] }}"
