---
- hosts: all
  remote_user: root
  gather_facts: no


  vars:
    env:
        HEKETI_CLI_SERVER: "http://{{servername}}"

  tasks:
  - name: Load Heketi topology
    heketi: action=load sshuser="{{ ssh_user }}"  userkey="{{ user_key }}" server="{{ servername }}"
            managehost={{ item.manage }} storagehost={{ item.storage }} zone={{ item.zone }}
            devices="{{ item.devices }}"
    with_items: hdict
    register: result

  - debug: msg="{{ result.results[0]['msg'] }}"
