---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  # Remove the filesystem signature. pvcreate fails if signature is present.
  # Safe to remove signatures, no harm done.
  # TODO: add wipe_signature=yes/no in future.
  - name: Clean up filesystem signature
    command: wipefs -af {{ item }}
    with_items: "{{ bricks | default([]) }}"
    when: item is defined
    ignore_errors: yes

  # Create pv on all the disks
  - name: Create Physical Volume
    pv: action=create disks={{ item }}
        options="--dataalignment {{ dalign }}k"
    with_items: "{{ bricks }}"
    register: result
    failed_when: "result.rc != 0 and 'Physical Volume Exists' not in result.msg"
