---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:

  - name: Add confs to glusterd.vol
    lineinfile:
        dest=/etc/glusterfs/glusterd.vol
        line="    option rpc-auth-allow-insecure on"
        insertbefore='end-volume'

  - name: Restart glusterd services
    service: name=glusterd state=restarted

  - name: Create a new user
    user: name="{{ smb_username }}"

  - name: Set smb password
    raw: (echo {{ item }}; echo {{ item }}) | smbpasswd -s -a "{{ smb_username }}"
    with_items: "{{ smb_password }}"

