---
# tasks file for unmounting
- name: Unmount the volumes
  gdeploy_mount:
    path={{item.path}}
    src={{item.src}}
    fstype={{item.src}}
    state={{item.state}}
  # with_items: "{{ path }}"
  with_items:
  - "{{ unmount_list}}"
